module.exports = {
    CLIENT_URL: "http://localhost:3000",
  
    ACCESS_TOKEN_SECRET: "@Yn6M7YOtVt8DGXX8NJ%eH6Jo4q2NWz4QKeKu",
    REFRESH_TOKEN_SECRET: "yka76*&SB&xlFD#QFafyWAYOS5mb8XH0$7p26td7#uXY3",
    ACTIVATION_TOKEN_SECRET: "FKQ59F63yF^0YQBg6GKQO8oVTfQi7bwsW4*3%&g7dIk$!jJtoi",
  
    MAILING_SERVICE_CLIENT_ID:
      "730915626392-tr0rmaitt7uh9vourksjfojihig75ft3.apps.googleusercontent.com",
    MAILING_SERVICE_CLIENT_SECRET: "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",
    MAILING_SERVICE_REFRESH_TOKEN:
      "1//044A9InRrJm2FCgYIARAAGAQSNgF-L9Ir9N0O_dxsch16A3u6Mcqy3sYiRklvo2VyhvdYhwr9j8e1yZzNeR-GLFs2W5XAi6QDzQ",
    SENDER_EMAIL_ADDRESS: "hmquan.20it5@vku.udn.vn",
  
    // CLOUD_NAME: "YOUR_CLOUD_NAME",
    // CLOUD_API_KEY: "YOUR_CLOUD_API_KEY",
    // CLOUD_API_SECRET: "YOUR_CLOUD_API_SECRET",
  
    // GOOGLE_SECRET: "YOUR_GOOGLE_SECRET",
    // FACEBOOK_SECRET: "YOUR_FACEBOOK_SECRET",
  };
  